// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjeKlasoru.Data;

#nullable disable

namespace ProjeKlasoru.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20240621221835_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ProjeKlasoru.Models.TblAlbum", b =>
                {
                    b.Property<int>("Album_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album_Adi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Album_Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("Album_No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album_Tur")
                        .HasColumnType("TEXT");

                    b.Property<string>("MenajerBilgisi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sanatci_bilgi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("yerli")
                        .HasColumnType("INTEGER");

                    b.HasKey("Album_Id");

                    b.ToTable("Tbl_Album");
                });
#pragma warning restore 612, 618
        }
    }
}
